build/CMakeCache.txt:
	mkdir -p build && cd build && cmake ..

.PHONY: %.cmake
%.cmake: build/CMakeCache.txt
	# Sets a variable (wildcard) to SETTING_VAL (undefined by default)
	if [ ! "$(shell grep -s '$(basename $@):' build/CMakeCache.txt | cut -d '=' -f2)" = "$(SETTING_VAL)" ]; then \
		cd build && cmake -D$(basename $@)=$(SETTING_VAL) ..; \
	fi

.PHONY: %.on
%.on:
	# This is necessary to set SETTING_VAL without inducing a lot of hacks
	@$(MAKE) SETTING_VAL=ON $(basename $@).cmake

.PHONY: %.off
%.off:
	# This is necessary to set SETTING_VAL without inducing a lot of hacks
	@$(MAKE) SETTING_VAL=OFF $(basename $@).cmake

.PHONY: %.target
%.target: build/CMakeCache.txt
	# Builds a target generated by cmake
	@$(MAKE) -Cbuild $(basename $@)
